# This is a nightly workflow based on https://gitlab.kitware.com/cmake/cmake/-/blob/master/Help/dev/testing.rst

name: Nightly-CI

# Controls when the workflow will run
on:
  # Periodic build
  schedule:
  # * is a special character in YAML so you have to quote this string
  # Execute a "nightly" build at 2 AM UTC 
  - cron:  '0 2 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: 'Linux-GCC-Matlab-${{ matrix.matlab_version }}' 
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        matlab_version: [R2020b, R2021a, R2021b, R2022a]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get install cmake build-essential libssl-dev
          cd ${GITHUB_WORKSPACE}/Dashboards/Scripts
          wget https://gitlab.kitware.com/cmake/dashboard-scripts/-/raw/master/cmake_common.cmake 

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.matlab_version }}
        
      - name: Run Nightly Test
        run: |
          export GHA_MATLAB_VERSION=${{ matrix.matlab_version }}
          env
          which matlab
          ctest --version
          ctest -S ${GITHUB_WORKSPACE}/Dashboards/Scripts/matlab_dashboard.cmake -V
